. "$HOME""/automation/env.sh"

LEFTBUTTONX=$(($(($SCREENWIDTH/2))-50))
RIGHTBUTTONX=$(($(($SCREENWIDTH/2))+50))
RIGHTBARX=$(($SCREENWIDTH-50))
UPPERROW=300;
ROWDELTA=50;
PREFIX="xte 'mousemove "
SUFFIX="' 'mouseclick 1'"
BUTTONSTART="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*0))$SUFFIX"
BUTTONSTOP="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*1))$SUFFIX"
BUTTONGOTO="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*3))$SUFFIX"
BUTTONGOTOTARGET="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*7))$SUFFIX"
BUTTONGOTOTARGETSTART="$PREFIX$RIGHTBARX $(($UPPERROW+$ROWDELTA*7))$SUFFIX"

BUTTONPAUSE="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*0))$SUFFIX"
BUTTONSTATION="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*1))$SUFFIX"
BUTTONFIND="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*3))$SUFFIX"

sh "$HOME""/pancake/pancake_startpage.sh"

"$SHELL" -c "$BUTTONGOTO"
"$SHELL" -c "$WAITLOADED 1"
"$SHELL" -c "$BUTTONGOTOTARGET"
"$SHELL" -c "$WAITLOADED 1"
"$SHELL" -c "$BUTTONGOTOTARGETSTART"
"$SHELL" -c "$WAITLOADED 1"
sleep 20
"$SHELL" -c "$CLEAN"
