. "$HOME""/automation/env.sh"

LEFTBUTTONX=$(($(($SCREENWIDTH/2))-50))
RIGHTBUTTONX=$(($(($SCREENWIDTH/2))+50))
RIGHTBARX=$(($SCREENWIDTH-50))
SETTINGSX=$(($(($SCREENWIDTH/10))+$(($SCREENWIDTH/5))*4))
UPPERROW=300;
ROWDELTA=50;
PREFIX="xte 'mousemove "
SUFFIX="' 'mouseclick 1'"
export BUTTONSTART="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*0))$SUFFIX"
export BUTTONSTOP="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*1))$SUFFIX"
export BUTTONGOTO="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*3))$SUFFIX"
export BUTTONGOTOTARGET="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*7))$SUFFIX"
export BUTTONGOTOTARGETSTART="$PREFIX$RIGHTBARX $(($UPPERROW+$ROWDELTA*7))$SUFFIX"
export BUTTONPAUSE="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*0))$SUFFIX"
export BUTTONSTATION="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*1))$SUFFIX"
export BUTTONFIND="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*3))$SUFFIX"
export BUTTONSETTINGS="$PREFIX$SETTINGSX $(($SCREENHEIGHT-50))$SUFFIX"
export BUTTONSETTINGSSYSTEM="$PREFIX$LEFTBUTTONX $(($UPPERROW+$ROWDELTA*4))$SUFFIX"
export BUTTONSETTINGSSYSTEMREBOOT="$PREFIX$RIGHTBARX $(($UPPERROW+$ROWDELTA*4))$SUFFIX"
export BUTTONSETTINGSSYSTEMREBOOTACCEPT="$PREFIX$RIGHTBUTTONX $(($UPPERROW+$ROWDELTA*3))$SUFFIX"

sh "$HOME""/pancake/pancake_startpage.sh"
"$SHELL" -c "$BUTTONSETTINGS"
"$SHELL" -c "$WAITLOADED 2"
"$SHELL" -c "$BUTTONSETTINGSSYSTEM"
"$SHELL" -c "$WAITLOADED 2"
"$SHELL" -c "$BUTTONSETTINGSSYSTEMREBOOT"
"$SHELL" -c "$WAITLOADED 2"
"$SHELL" -c "$BUTTONSETTINGSSYSTEMREBOOTACCEPT"
"$SHELL" -c "$WAITLOADED 2"
"$SHELL" -c "$BUTTONSETTINGSSYSTEMREBOOTACCEPT"
"$SHELL" -c "$WAITLOADED 2"
"$SHELL" -c "$CLEAN"
