"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/backup/backup.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/pancake/pancake_start_BatteryCharged.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/flatastic/flatastic_toilettenpapier.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/flatastic/flatastic_zitronentee.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/pancake/pancake_toTarget_BatteryCharged_loadMapUp.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/websiteChanged/checkSite.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/prospektRewe/rewe_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/prospektLidl/lidl_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/prospektHolAb/holAb_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/prospektEdeka/edeka_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/prospektAldi/aldi_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/payback/payback_login.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/automation/dailyscripts.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/bplaced/bplaced_login.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/couponsBurgerKing/couponsBurgerKing.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/AldiTalkEvn/aldi_load.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/automation/utils_watchFreeSpace.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/automation/utils_cleanTspPancake.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/automation/utils_cleanCronPancake.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/pancake/pancake_runScript_batteryCharged.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/whatsapp/whatsapp_plannedMessage.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/whatsapp/carola.sh
"$SHELL" "$HOME""/automation/tspRemoveFilter.sh" "$HOME"/Netzclub/netzclub.sh
